package First.Server;

import First.Client.DaemonThread;

import com.ibm.dthreads.DThreadExecutionContext;
import com.ibm.dthreads.DistributedExecutionManager;
import com.ibm.dthreads.SPMDDistributedExecutionManager;

public class Driver
{
    public static void main(String args[])
    {
        DaemonThread dwin = new DaemonThread();
        DistributedExecutionManager dman = new SPMDDistributedExecutionManager(0);
        DThreadExecutionContext con = new DThreadExecutionContext(5);
        dman.execute(dwin, con);
    }
}

File First/Client/DaemonThread.java
package First.Client;

import com.ibm.dthreads.DThread;
import com.ibm.dthreads.DRunnable;
/**
 *
 * @author  Administrator
 */


class ChildWin extends javax.swing.JFrame {
    
       
    
    /** Creates new form ChildWin */
    public ChildWin(int id) {
        initComponents();
      
        jTextArea1.setText("Child program " + id  + "finished");
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jTextArea1 = new javax.swing.JTextArea();

        getContentPane().setLayout(new java.awt.BorderLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DPPEJ Client");
        setFont(new java.awt.Font("Arial", 0, 12));
        setForeground(java.awt.Color.white);
        setName("f");
        jTextArea1.setColumns(20);
        jTextArea1.setRows(10);
        jTextArea1.setTabSize(4);
        jTextArea1.setToolTipText("DPPEJ Child Window");
        getContentPane().add(jTextArea1, new java.awt.BorderLayout().CENTER);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
    
}

    /**
     * @run method called by the server driver
     */
   public  class DaemonThread extends DThread
    {
        ChildWin c;  
        
        public DaemonThread()
          {

      
              
          }
        public void run() {
		 int id;
 		id =  DThread.getContext().getIdentity();
            c = new ChildWin(id);
                 c.setVisible(true);
                
                
                //not necessary
                //ObjectMP messagepasser = DThread().getContext().getMP();
                
                //not necessary in this case
                //int no_Threads = DThread.getContext().getNumberOfThreads();
                
            }
    }
